"""add highlight tables

Revision ID: 393bc4616071
Revises: 5a677de22f52
Create Date: 2026-01-23 22:53:54.069520

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "393bc4616071"
down_revision: str | Sequence[str] | None = "5a677de22f52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "highlight",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "case_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("tag", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("para_num", sa.Integer(), nullable=True),
        sa.Column(
            "section_header",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
        sa.Column(
            "created_by", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_highlight_case_id"), "highlight", ["case_id"], unique=False
    )
    op.create_table(
        "highlight_comment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("highlight_id", sa.Uuid(), nullable=False),
        sa.Column(
            "author", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["highlight_id"], ["highlight.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_class_owner_id"), table_name="class")
    op.drop_index(op.f("ix_conversation_class_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_owner_id"), table_name="conversation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_conversation_owner_id"), "conversation", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_class_id"), "conversation", ["class_id"], unique=False
    )
    op.create_index(op.f("ix_class_owner_id"), "class", ["owner_id"], unique=False)
    op.drop_table("highlight_comment")
    op.drop_index(op.f("ix_highlight_case_id"), table_name="highlight")
    op.drop_table("highlight")
    # ### end Alembic commands ###
