"""add unique constraints to course enrollment and week

Revision ID: a124e721864c
Revises: adb0f2ee06fa
Create Date: 2026-01-24 04:44:57.022208

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a124e721864c"
down_revision: str | Sequence[str] | None = "adb0f2ee06fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_course_enrollment_course_member",
        "course_enrollment",
        ["course_id", "member_id"],
    )
    op.create_unique_constraint(
        "uq_week_course_number", "week", ["course_id", "week_number"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_week_course_number", "week", type_="unique")
    op.drop_constraint(
        "uq_course_enrollment_course_member", "course_enrollment", type_="unique"
    )
    # ### end Alembic commands ###
