"""add course week enrollment tables

Revision ID: adb0f2ee06fa
Revises: 393bc4616071
Create Date: 2026-01-24 04:12:26.039898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "adb0f2ee06fa"
down_revision: Union[str, Sequence[str], None] = "393bc4616071"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column(
            "semester", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_course_code"), "course", ["code"], unique=False)
    op.create_index(op.f("ix_course_semester"), "course", ["semester"], unique=False)
    op.create_table(
        "course_enrollment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column(
            "member_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum("coordinator", "instructor", "tutor", "student", name="courserole"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["course.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_enrollment_member_id"),
        "course_enrollment",
        ["member_id"],
        unique=False,
    )
    op.create_table(
        "week",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("visible_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["course.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("week")
    op.drop_index(
        op.f("ix_course_enrollment_member_id"), table_name="course_enrollment"
    )
    op.drop_table("course_enrollment")
    op.drop_index(op.f("ix_course_semester"), table_name="course")
    op.drop_index(op.f("ix_course_code"), table_name="course")
    op.drop_table("course")
    # ### end Alembic commands ###
